version: '3.6'
services:
  web-server:
    build: 
      context: web-server/
      args:
       - VERSION=master
       - CONTEXT=Wallet
    image: mooo-wallet-web-server:0.0.2
    ports:
     - "4003:8080"
    restart: unless-stopped
  web-client:
    build: 
      context: web-client/
      args:
       - VERSION=master
       - ENV=${WEB_CLIENT_ENV}
    image: mooo-wallet-web-client-${WEB_CLIENT_ENV}:0.0.2
    ports:
     - "3003:80"
    command: httpd -D FOREGROUND
    restart: unless-stopped
