apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-server
    spec:
      containers:
      - image: docker.pkg.github.com/youssefgh/tcp-rest-proxy/tcp-rest-proxy:0.0.1
        name: web-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
